### ISSUE TITLE
v3.0.3 release checklist

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#1880]
Issues needing to be addressed prior to release:

- [x] detect/enforce min PMIx version at runtime
- [ ] update VERSION and news
        - [ ] PMIx
        - [ ] PRRTE
- [ ] update PMIx and PRRTE release branches with relevant master branch commits
       - [x] PMIX
       - [ ] PRRTE
- [x] PRRTE tools themselves are not impacted by cmd line MCA param settings
