### ISSUE TITLE
Checklist for "stable" landing point

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#2020]
With the project winding down, it is time to define a stable landing point where we can leave it for those wanting to use it. This means:

- removing all stale code, particularly components that aren't actively used
- collapsing frameworks into single code directories where multiple variations are not required (e.g., rtc)
- reducing complexity wherever possible

We'll keep a checklist here as we work thru the process - will culminate in a new PRRTE v4 release series

Code pruning and correction
- [x] Remove "likwid" mapper - never implemented
- [x] Remove "slurm" and "mpich" personalities - never fully implemented nor used
- [x] Collapse "rtc" framework
- [x] Collapse "oob" framework - consolidate the messaging system and refactor it
- [x] Remove "psched" tool - being replaced by external "dynasched" Python project
- [x] Revamp tool system - replace individual tools (e.g., "pterm") with options to "prte" itself to remove conflicts with other packages, need to design this as we must retain "prterun" and "prun" as separate cmds
- [x] Resolve "permanent" solution to the Slurm plm problem - use new launcher lib _if_ it becomes available, otherwise may need to remove envar support for the internal "srun" cmd line options (see also: #1974)
- [x] Raise min HWLOC version to 2.1.0
- [x] Fix the "show-help" mess by clarifying the source of what gets installed - either in the top-level src/doc/show_help directory, or in the localized ones
- [x] Resolve known pending issues - one issue remains, with no progress being made on it. It will be resolved as part of the scheduler integration effort.
    * https://github.com/openpmix/prrte/issues/1773
- [x] Make one last "production" release - v3.0.7

Enhancements
- [ ] Add PRRTE-internal resiliency support - recover connections to grandparents when parent connection is lost, restore parent connection if/when parent returns, number collective messages to ensure replay when necessary

Scheduler integration
- [x] Resolve question of moving scheduler integration support into separate branch - Just leave it here. We now have adequate CI to avoid breaking others, so we should be okay.
- [ ] Complete node extension support for adding nodes on-the-fly
- [ ] Complete session directive support - e.g., session/job preemption

**Comment by naughtont3** [comment]
>     * [ ]  Resolve "permanent" solution to the Slurm plm problem - use new launcher lib _if_ it becomes available, otherwise may need to remove envar support for the internal "srun" cmd line options

Quick follow-up after 3oct2024 teleconf, I was mistaken and the `SLURM_VERSION` is *not* exported as an envvar within the allocation. Appears you must go through one of the utilities (e.g., `srun --version`, `scontrol show config | grep SLURM_VERSION`).

**Comment by rhc54** [comment]
If you just get an allocation (`salloc` and no `srun`) is there anything you can see that might give us a hint as to version, even if it doesn't give us a direct value?

**Comment by naughtont3** [comment]
Unfortunately, i do not see anything that would give an indication (`salloc` and then `env | grep SLURM`).

**Comment by rhc54** [comment]
The "oob collapse" has been completed - see https://github.com/openpmix/prrte/pull/2035

**Comment by edgargabriel** [comment]
@rhc54 Is the fix of https://github.com/open-mpi/ompi/issues/12682 already in as well?

**Comment by rhc54** [comment]
Yes - everything is caught up. I have one thing still in the queue, but it's being tracked over in the PMIx repo. Otherwise, everything still needing attention is listed above, and anything else is done. The fix you ask about is also in the release branch awaiting update over in OMPI.

**Comment by rhc54** [comment]
Closing this as completed. The enhancements are not complete, but it isn't clear they will ever be addressed as there doesn't appear to be any immediate interest in them. We have identified some bugs that have been fixed, and the flow of bugs is slowing to a trickle as things stabilize. The group support has been revamped to isolate them from the other collectives so we minimize cross-operation clashes when changes are made.

So I think we can declare that we have arrived at a stable landing point.
