### ISSUE TITLE
Additional Documentation Items

### ISSUE THREAD

**Issue by jjhursey** [openpmix/prrte#830]
Below is a list of items that need to be added to the PRRTE documentation

- [ ] Multi-job connect/accept from [this thread](https://github.com/openpmix/prrte/issues/398#issuecomment-795628306)
- [ ] Precedence over for runtime parameters from Issue #413 
- [x] Cleanup term usage for things like `:HWTCPUS` for the `--map-by` option. is it a "qualifer" or "modifier" or ...?
- [ ] PRRTE version compatibility with OpenPMIx https://github.com/openpmix/prrte/issues/595
- [ ] `--map-by` `:SPAN` qualifier Per https://github.com/openpmix/prrte/issues/674
- [ ] `--preload-files` and `--preload-binary` options https://github.com/open-mpi/ompi/issues/77
- [ ] `--output` and `--display` CLI options from https://github.com/openpmix/prrte/pull/866
- [ ] FAQ: Entry on LSF configuration for CORAL systems. See Issue #871

**Comment by jjhursey** [comment]
Per teleconf March 18, 2021:
 * "`:HWTCPUS` qualifier to the `--map-by` option" (not modifier) @jsquyres Do you have an opinion here?

**Comment by jjhursey** [comment]
I am no longer able to work on this ticket, but I did finish one aspect of it in https://github.com/openpmix/prrte/pull/889
